#!/usr/bin/env python
# -*- coding: utf-8 -*-
#Ejercicio 10
m1 = {}
m2 = {} 
m3 = {} m =1
while (m < 3):
    print ("Ingrese los valores de la matriz %s:" % m)
    for i in range(3):
        mm = []
        for j in range(3):
            valor = input("\tFila "+str(i+1)+" columna "+str(j+1)+": ")
            mm.append(valor)
            if m == 1:
                m1[i] = mm
            elif m == 2:
                m2[i] = mm
        print "+------------------------------------------------+"
m += 1
for i in range(3):
    mm = []
    for j in range(3):
        mm.append(m1[i][j] + m2[i][j])
        m3[i] = mm
for i in range(3):
    print str(m1[i])+'\t'+str(m2[i])+'\t'+str(m3[i])
