#!/usr/bin/env python
# -*- coding: utf-8 -*-
#Ejercicio 1
num1 = raw_input("Ingrese primer numero entre 2 y 20: ")
num2 = raw_input("Ingrese segundo numero entre 2 y 20: ")


if (int (num1) > 2 and int (num1) < 20) and (int (num2) > 2 and int (num2) < 20):
suma = num1 + num2
 el	
else: print "Ingrese números emtre 2 y 20"

if num2 >5 and num2 <20:
	print "El numero dos esta bien"

if (int(num1) >5 and int (num1) <20) and (int(num2) >5 and int(num2)<20):
	print "Ambos numeros estan bien"


