#!/usr/bin/env python
# -*- coding: utf-8 -*-

import mysql.connector
cnx = mysql.connector.connect(user='dbuser',password='Asqldm1010',host='192.168.15.121',database='HAYHOLA')
cursor = cnx.cursor()
q_consulta = ("SELECT * FROM H123 ORDER BY id")
cursor.execute(q_consulta)
consulta = cursor.fetchall()
print consulta
if consulta:
    for q in consulta:
        print q[1]
else:
    print "No hay conexión"
